apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: app
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdEAxMjM=  # base64 encoded value of 'root@123'
  MYSQL_PASSWORD: cm9vdEAxMjM=  # base64 encoded value of 'root@123'
